import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NotificationBar from "./components/globalComponents/NotificationBar";
import Navbar from "./components/globalComponents/Navbar";
import Footer from "./components/globalComponents/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "BANDAGE",
  description: "Generated by Ashna Ghazanfar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className="max-w-[1440px] mx-auto text-[#252B42] ]">
        <header>
          <NotificationBar />
          <Navbar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
