import Link from "next/link";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-red-600">
          <nav className="flex justify-between p-2 text-white">
            <h1>
              <Link href="/">Pizza Party</Link>
            </h1>
            <div className="flex gap-3 justify-center items-center">
              <Link href="/">Home</Link>
              <Link href="/pizzas">Pizzas</Link>
          
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
